apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimiter
  template:
    metadata:
      labels:
        app: ratelimiter
    spec:
      containers:
        - name: ratelimiter
          image: ratelimiter:latest
          imagePullPolicy: Never
